# .travis.yml
language:
  - node_js
node_js:
  - '8'
branches:
  - master
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
env:
  global:
    secure:
    "E5kcWOQ5HAm9V4ll30xVPzLBaXRtzVf2m4ItovZwNN8N4D6U8QF83H1jCEheFNDYiGavS8s6MHjBmLijlPbq+l4T+M31mzjyHJssYndVbSuA5JkT3R5BDAkaeRLlMKC5GEQK40vAfIUQ9hnvDCZw5dn53P1VabLaysTo95B2MqhlbVHzFE/ge5OPg7DrfW/Maslua/b3+9ouR2IR7fsa3R6BrmJGNycNrBio19SCBSYCA3kNLlyusS/S2i+vaYq2q5yxGTOPPmajg7trrxhTQhoz86US/Bnhq1+BB91PNc5tHn6mTdo1zdV5GwmyEFsHEJ4rfA6OA5en2qR2zVYpVTOuO/Cvwwl2aDhzPHw+28qELbRc+oPddUOK8AbfdaBiTd441gqqf4w9Wo/vBfil1cwRoNKjB1yij4HPsfuC/AdDGZm+MWbl+jpElSqJEibjK97SpBh4n90hpNhyIJKji2wYZn0oVAjk4aJ+0aDVGeN72qEazISepteowx2jtVpZVOmzX4uEAkt1fSB/eezgh8jKgN0uHvY5Fh+7BpVQN9i1Luj/nfGo0AWj/VoTkC1GN+J21fZA6pkcX9wvbxP5ul2LyWna6uAf7lidTptjrZe7kmYUsPJ/Dy/tMaSXMT1NsM4HQCLII2E54E0ChYosl0fGPBZGbWH4g9HY063FYJo="